---
title: "UnrecogSource Descriptive Analysis"
author: "Will Hopper"
date: "`r format(Sys.Date(), '%m-%d-%Y')`"
output: html_document
---

```{r include=FALSE}
knitr::opts_chunk$set(echo=FALSE, fig.align="center")
library(rprojroot)
library(ggplot2)
library(ggExtra)
library(scales)
library(tidyr)
library(dplyr)
root_dir <- rprojroot::is_rstudio_project$find_file()
source(file.path(root_dir, "R", "preprocessing.R"))
```

```{r load_data}
unrecog_source <- load_data(file.path(root_dir, "data"))
# Remove trials with no response from further analysis
missing_trials <- filter(unrecog_source, is.na(response))
unrecog_source <- filter(unrecog_source, !is.na(response))
# Separate null/catch trials from real trials
catch_trials <- filter(unrecog_source, null)
unrecog_source <- filter(unrecog_source, !null)
# Separate source and recognition task trials, for convienience
source_data <- filter(unrecog_source, task == "source")
recog_data <- filter(unrecog_source, task == "recog")
```

```{r accuracy, fig.width=7, fig.height=7}
subject_acc <- group_by(unrecog_source, subj, task) %>%
  summarise(acc = mean(corr))

{ ggplot(spread(subject_acc, task, acc),
       aes(x=source, y=recog)) +
  geom_point(size= 2) +
  scale_x_continuous("Source Memory Accuracy", limits = c(0,1),
                     labels = scales::percent) +
  scale_y_continuous("Recognition Memory Accuracy", limits = c(0,1),
                     labels = scales::percent) +
  coord_fixed() +
  ggtitle("Source vs. Recognition Memory") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=0.5))
} %>%
  ggMarginal(type = "histogram")
```

```{r encoding_tasks, fig.width=12, fig.height=7}
encoding_tasks <- filter(unrecog_source, type != "lure") %>%
  group_by(subj, encoding, task) %>%
  summarise(acc = mean(corr))

ggplot(encoding_tasks, aes(x=acc, fill=encoding)) +
  geom_histogram(bins=20, alpha=.4, position="identity") +
  facet_grid(~task, labeller = as_labeller(c("source"="Source",
                                             "recog"="Recognition"))
             ) +
  scale_fill_discrete(guide = guide_legend(override.aes = list(alpha=1))) +
  scale_x_continuous("Hit Rate (studied items only)") +
  ggtitle("Accuracy by Encoding Task") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=0.5))
```

```{r word_frequency, fig.width=12, fig.height=7}
word_freq <- group_by(unrecog_source, subj, wf, task) %>%
  summarise(acc = mean(corr))

ggplot(spread(word_freq, task, acc), aes(x=source, y=recog)) +
  geom_point(size=2) +
  geom_rug(size=0.1) +
  facet_grid(~wf, labeller = as_labeller(c("LF"="Low Frequency",
                                           "HF"="High Frequency"))
             ) +
  scale_x_continuous("Source Memory Accuracy", limits = c(0,1),
                     labels = scales::percent) +
  scale_y_continuous("Recognition Memory Accuracy", limits = c(0,1),
                     labels = scales::percent) +
  coord_fixed() +
  ggtitle("Accuracy by Word Frequency") +
  theme_bw(base_size = 16) +
  theme(plot.title = element_text(hjust=0.5))
```

```{r bias}
bias_effects <- group_by(recog_data, subj, bias, type) %>%
  summarise(p = mean(corr)) %>%
  spread(type, p) %>%
  mutate(lure = 1-lure,
         diff = target-lure) %>%
  rename(HR = target, FAR = lure)

avg_bias_effects <- group_by(bias_effects, bias) %>%
  summarise_at(c("FAR", "HR"), mean)

ggplot(bias_effects, aes(x=FAR, y=HR, color=bias)) +
  geom_point() +
  geom_path(mapping=aes(group=subj), color="black") +
  geom_point(data=avg_bias_effects, stroke=3, shape=4)
```

```{r catch_trials, fig.height=7, fig.width=7}
catch_effects <- filter(catch_trials, task=="recog") %>%
  count(subj, bias, response) %>%
  complete(subj, bias, response, fill = list(n=0)) %>% # not 100% sure about this step...
  spread(response, n) %>%
  rename(new=m, old=z)

ggplot(catch_effects, aes(x=old, y=new, color=bias)) +
  geom_point(size=2) +
  geom_abline(slope=1,intercept=0) +
  ggtitle("Catch trial decision pattern") +
  coord_fixed()
```

```{r conditional}
conditional_acc_by_subj <- 
  inner_join(select(source_data, subj, item, bias, source_acc = corr),
             select(recog_data, subj, item, bias, recog_acc = corr),
             by = c("subj","item","bias")) %>%
  group_by(subj, bias, recog_acc) %>%
  summarise(source_acc = mean(source_acc),
            n_obs = n())

conditional_acc <- group_by(conditional_acc_by_subj, bias, recog_acc) %>%
  summarise(source_acc = mean(source_acc))
```

```{r conditional_plots, fig.width=8, fig.height=7}
ggplot(conditional_acc_by_subj, aes(x=factor(recog_acc), y=source_acc, color=bias)) +
  geom_point(position = position_dodge(width=.5), alpha=.5, shape=16, size=2) +
  geom_point(data=conditional_acc, position = position_dodge(width=.5),
             size=4, shape=4, stroke=3) +
  scale_x_discrete("Recognition Decision", labels=c(`0`="Miss", `1`="Hit")) +
  scale_y_continuous("Source Accuracy") +
  scale_color_discrete("Bias")
```

